### ISSUE TITLE
Proposal: Let's do versioning

### ISSUE THREAD

**Issue by fujimotos** [edsiper/chunkio#52]
This is just a casual proposal that (I think) would help the development.

**Backgrond**

We use chunkio as a library in Fluen Bit. Right now the workflow is that
(1) we do some development on chunkio and then (2) occationally sync the
result into fluent/fluent-bit.

The synchronization is done by manually copying files and adding a commit
like below:

    commit 0e000ca45cd70731896008d1cf1a34c3caf5a88f
    Date:   Thu Sep 26 11:59:29 2019 -0600

        lib: chunkio: sync changes, details below:
        
        - validate if fallocate is supported
        - new trace mode
        - new api call to retrieve metadata size
        - fix crash when opening a corrupted file
        - new unit test issue_51

But it's kinda opaque from the commit which version of chunkio is in use.
We need to look into the history and figure out is which is corresponding
to which.

If there is a versioning, we can simply say:

    commit 0e000ca45cd70731896008d1cf1a34c3caf5a88f
    Date:   Thu Sep 26 11:59:29 2019 -0600

        lib: chunkio: update version from v1.0 to v1.1
        
In my opinion, this is much clearer. The commit message clearly tells us
that the synchronization is done in a well-defined point.

**Proposal**

Let's call 4f197e0, say, v1.0.0 and do versioning thereafter.

**Comment by edsiper** [comment]
hi @fujimotos . sorry for the late reply, I did not see this issue.

Makes totally sense. Just now I am going to do some changes and start doing the versioning right after that.

**Comment by edsiper** [comment]
v1.0.0 is out :)

**Comment by fujimotos** [comment]
> v1.0.0 is out :)

@edsiper Thank you!
